name: Lint JSON (Translations)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install JSON linter
        run: npm install -g jsonlint

      - name: Lint JSON files in /translations
        run: |
          echo "Linting JSON files in /translations..."
          if [ -d "./translations" ]; then
            find ./translations -type f -name "*.json" -print0 | xargs -0 -n1 jsonlint -q
          else
            echo "No /translations directory found."
          fi
